Nama = input("Nama                 : ")
NIM = input("NIM                  : ")
Kelas = input("Kelas Paralel        : ")
TTL = input("Tempat/Tanggal Lahir : ")
Alamat = input("Alamat               : ")
hobby = input("Hobby                : ")
hp = input("No. HP               : ")
print("\nNama                 : %s" %Nama)
print("NIM                  : %s" %NIM)
print("Kelas Paralel        : %s" %Kelas)
print("Tempat/Tanggal Lahir : %s" %TTL)
print("Alamat               : %s" %Alamat)
print("Hobby                : %s" %hobby)
print("No. HP               : %s" %hp)