phi = 22/7
r = input()
t = input()
r = float(r)
t = float(t)
v = phi * r * r * t
l = 2 * phi * r * (r + t)
k = 2 * phi * r
print("Volume = %.2f" %v)
print("Luas = %.2f" %l)
print("Keliling = %.2f\n" %k)
r1, t1 = input().split()
r1 = float(r1)
t1 = float(t1)
v1 = phi * r1 * r1 * t1
l1 = 2 * phi * r1 * (r1 + t1)
k1 = 2 * phi * r1
print("Volume = %.2f" %v1)
print("Luas = %.2f" %l1)
print("Keliling = %.2f\n" %k1)