a, b, i, j, x, y = input().split()
a = float(a)
b = float(b)
i = float(i)
j = float(j)
x = float(x)
y = float(y)
Hasil = (a-b)*(i/j)-(x+y)
print("%.3f\n" %Hasil)
A, B = input().split()
I, J = input().split()
X, Y = input().split()
A = float(A)
B = float(B)
I = float(I)
J = float(J)
X = float(X)
Y = float(Y)
HASIL = (A-B)*(I/J)-(X+Y)
print("%.3f\n" %HASIL)